import { Product } from '../lib/types';

export const products: Product[] = [
  // Višnjevac
  {
    id: '1',
    name: 'Višnjevac 0.7L',
    description: 'Domaći liker od višanja, prepun prirodnih aroma. Pažljivo destiliran u našoj obiteljskoj destileriji.',
    price: 17.00,
    image: 'https://placehold.co/300x200/8B0000/ffffff?text=Vi%C5%A1njevac+0.7L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '2',
    name: 'Višnjevac 0.04L',
    description: 'Domaći liker od višanja u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: 'https://placehold.co/300x200/8B0000/ffffff?text=Vi%C5%A1njevac+0.04L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '3',
    name: 'Višnjevac 0.2L',
    description: 'Domaći liker od višanja u manjoj bočici.',
    price: 7.00,
    image: 'https://placehold.co/300x200/8B0000/ffffff?text=Vi%C5%A1njevac+0.2L',
    category: 'Likeri',
    unit: 'kom',
  },
  // Haskap Liker
  {
    id: '4',
    name: 'Haskap Liker 0.7L',
    description: 'Liker od haskap bobica, iznimno bogat antioksidansima i prirodnog voćnog okusa.',
    price: 20.00,
    image: 'https://placehold.co/300x200/4B0082/ffffff?text=Haskap+Liker+0.7L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '5',
    name: 'Haskap Liker 0.04L',
    description: 'Liker od haskap bobica u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: 'https://placehold.co/300x200/4B0082/ffffff?text=Haskap+Liker+0.04L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '6',
    name: 'Haskap Liker 0.2L',
    description: 'Liker od haskap bobica u manjoj bočici.',
    price: 8.00,
    image: 'https://placehold.co/300x200/4B0082/ffffff?text=Haskap+Liker+0.2L',
    category: 'Likeri',
    unit: 'kom',
  },
  // Liker Maslina
  {
    id: '7',
    name: 'Liker Maslina 0.5L',
    description: 'Jedinstveni liker od maslina, delikatan okus mediteranskog voća u bočici.',
    price: 30.00,
    image: 'https://placehold.co/300x200/556B2F/ffffff?text=Liker+Maslina+0.5L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '8',
    name: 'Liker Maslina 0.04L',
    description: 'Liker od maslina u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: 'https://placehold.co/300x200/556B2F/ffffff?text=Liker+Maslina+0.04L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '9',
    name: 'Liker Maslina 0.2L',
    description: 'Liker od maslina u manjoj bočici.',
    price: 12.00,
    image: 'https://placehold.co/300x200/556B2F/ffffff?text=Liker+Maslina+0.2L',
    category: 'Likeri',
    unit: 'kom',
  },
  // Zagorska Šljivovica
  {
    id: '10',
    name: 'Zagorska Šljivovica 0.7L',
    description: 'Tradicionalna zagorska šljivovica, destilirana prema starim recepturama naše obitelji.',
    price: 20.00,
    image: 'https://placehold.co/300x200/4A235A/ffffff?text=%C5%A0ljivovica+0.7L',
    category: 'Rakija',
    unit: 'kom',
  },
  {
    id: '11',
    name: 'Zagorska Šljivovica 0.5L',
    description: 'Tradicionalna zagorska šljivovica u bočici od pola litre.',
    price: 20.00,
    image: 'https://placehold.co/300x200/4A235A/ffffff?text=%C5%A0ljivovica+0.5L',
    category: 'Rakija',
    unit: 'kom',
  },
  {
    id: '12',
    name: 'Zagorska Šljivovica 0.04L',
    description: 'Zagorska šljivovica u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: 'https://placehold.co/300x200/4A235A/ffffff?text=%C5%A0ljivovica+0.04L',
    category: 'Rakija',
    unit: 'kom',
  },
  // Liker Mušmula
  {
    id: '13',
    name: 'Liker Mušmula 0.7L',
    description: 'Liker od mušmule, rijetko voće pretvoreno u izvanredan domaći liker.',
    price: 20.00,
    image: 'https://placehold.co/300x200/B8860B/ffffff?text=Liker+Mu%C5%A1mula+0.7L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '14',
    name: 'Liker Mušmula 0.04L',
    description: 'Liker od mušmule u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: 'https://placehold.co/300x200/B8860B/ffffff?text=Liker+Mu%C5%A1mula+0.04L',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '15',
    name: 'Liker Mušmula 0.2L',
    description: 'Liker od mušmule u manjoj bočici.',
    price: 8.00,
    image: 'https://placehold.co/300x200/B8860B/ffffff?text=Liker+Mu%C5%A1mula+0.2L',
    category: 'Likeri',
    unit: 'kom',
  },
  // EKO Ocat od Mandarine
  {
    id: '16',
    name: 'EKO Ocat od Mandarine 0.25L',
    description: 'Ekološki ocat od mandarine, prirodno fermentiran bez konzervansa. Savršen za salate i mariniranje.',
    price: 5.00,
    image: 'https://placehold.co/300x200/FF8C00/ffffff?text=Ocat+Mandarina',
    category: 'EKO',
    unit: 'kom',
  },
  // EKO Haskap Svježi
  {
    id: '17',
    name: 'EKO Haskap Svježi 1kg',
    description: 'Svježe haskap bobice iz ekološkog uzgoja, iznimno bogate antioksidansima i vitaminom C.',
    price: 14.00,
    image: 'https://placehold.co/300x200/4B0082/ffffff?text=Haskap+Svje%C5%BEi',
    category: 'EKO',
    unit: '1kg',
  },
];