import { Product } from '../lib/types';

export const products: Product[] = [
  // Višnjevac
  {
    id: '1',
    name: 'Višnjevac 0.7L',
    description: 'Domaći liker od višanja, prepun prirodnih aroma. Pažljivo destiliran u našoj obiteljskoj destileriji.',
    price: 17.00,
    image: '/products/visnjevac-07.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '2',
    name: 'Višnjevac 0.04L',
    description: 'Domaći liker od višanja u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: '/products/visnjevac-004.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '3',
    name: 'Višnjevac 0.2L',
    description: 'Domaći liker od višanja u manjoj bočici.',
    price: 7.00,
    image: '/products/visnjevac-02.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  // Haskap Liker
  {
    id: '4',
    name: 'Haskap Liker 0.7L',
    description: 'Liker od haskap bobica, iznimno bogat antioksidansima i prirodnog voćnog okusa.',
    price: 20.00,
    image: '/products/haskap-07.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '5',
    name: 'Haskap Liker 0.04L',
    description: 'Liker od haskap bobica u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: '/products/haskap-004.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '6',
    name: 'Haskap Liker 0.2L',
    description: 'Liker od haskap bobica u manjoj bočici.',
    price: 8.00,
    image: '/products/haskap-02.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  // Liker od Zagorskih Maslina
  {
    id: '7',
    name: 'Liker od Zagorskih Maslina 0.5L',
    description: 'Jedinstveni liker od zagorskih maslina u elegantnoj dekanterskoj bočici. Delikatan okus mediteranskog voća s dušom Zagorja.',
    price: 30.00,
    image: '/products/maslina-05.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '8',
    name: 'Liker od Zagorskih Maslina 0.04L',
    description: 'Liker od zagorskih maslina u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: '/products/maslina-004.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  {
    id: '9',
    name: 'Liker od Zagorskih Maslina 0.2L',
    description: 'Liker od zagorskih maslina u manjoj bočici.',
    price: 12.00,
    image: '/products/maslina-02.jpeg',
    category: 'Likeri',
    unit: 'kom',
  },
  // Zagorska Šljivovica
  {
    id: '10',
    name: 'Zagorska Šljivovica 0.7L',
    description: 'Tradicionalna zagorska šljivovica, destilirana prema starim recepturama naše obitelji.',
    price: 20.00,
    image: '/products/sljivovica-07.jpeg',
    category: 'Rakija',
    unit: 'kom',
  },
  {
    id: '11',
    name: 'Zagorska Šljivovica 0.5L',
    description: 'Tradicionalna zagorska šljivovica u posebnoj dekanterskoj bočici.',
    price: 20.00,
    image: '/products/sljivovica-05.jpeg',
    category: 'Rakija',
    unit: 'kom',
  },
  {
    id: '12',
    name: 'Zagorska Šljivovica 0.04L',
    description: 'Zagorska šljivovica u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: '/products/sljivovica-004.jpeg',
    category: 'Rakija',
    unit: 'kom',
  },
  // Lozovača
  {
    id: '21',
    name: 'Lozovača 0.7L',
    description: 'Domaća lozovača, destilirana od grožđa s naših vinograda. Čist i osvježavajući okus tradicije.',
    price: 20.00,
    image: '/products/lozovaca-07.jpeg',
    category: 'Rakija',
    unit: 'kom',
  },
  // Liker Mušmula
  {
    id: '13',
    name: 'Liker Mušmula 0.7L',
    description: 'Liker od mušmule, rijetko voće pretvoreno u izvanredan domaći liker.',
    price: 20.00,
    image: '/products/musmula.jpeg',
    category: 'Likeri',
    unit: 'kom',
    comingSoon: true,
  },
  {
    id: '14',
    name: 'Liker Mušmula 0.04L',
    description: 'Liker od mušmule u mini bočici — idealno za degustaciju.',
    price: 2.50,
    image: '/products/musmula.jpeg',
    category: 'Likeri',
    unit: 'kom',
    comingSoon: true,
  },
  {
    id: '15',
    name: 'Liker Mušmula 0.2L',
    description: 'Liker od mušmule u manjoj bočici.',
    price: 8.00,
    image: '/products/musmula.jpeg',
    category: 'Likeri',
    unit: 'kom',
    comingSoon: true,
  },
  // EKO Haskap Svježi
  {
    id: '17',
    name: 'EKO Haskap Svježi 1kg',
    description: 'Svježe haskap bobice iz ekološkog uzgoja, iznimno bogate antioksidansima i vitaminom C.',
    price: 14.00,
    image: '/products/haskap-svjezi.jpg',
    category: 'EKO',
    unit: '1kg',
    comingSoon: false,
  },
  // EKO Ocat od Mandarine
  {
    id: '16',
    name: 'EKO Ocat od Mandarine 0.25L',
    description: 'Ekološki ocat od mandarine, prirodno fermentiran bez konzervansa. Savršen za salate i mariniranje.',
    price: 5.00,
    image: '/products/ocat-mandarina.jpeg',
    category: 'EKO',
    unit: 'kom',
  },
  // Poklon paketi
  {
    id: '18',
    name: 'Zagorski Gušti',
    description: 'Poklon kutija s tri domaća proizvoda: Haskap liker 0.2L, Zagorska Šljivovica 0.5L i Višnjevac 0.2L — sve umotano u slamu s crvenom mašnom. Savršen poklon za ljubitelje autentičnih zagorskih okusa.',
    price: 25.00,
    image: '/products/zagorski-gusti.jpeg',
    category: 'Poklon paketi',
    unit: 'kom',
  },
  {
    id: '19',
    name: 'Rapsodija Okusa',
    description: 'Raskošna poklon kutija s bogatim izborom: Liker od Zagorskih Maslina 0.5L, Višnjevac 0.2L, Haskap liker 0.2L i četiri mini bočice za degustaciju. Savršeno za posebne prigode i prave gurmane.',
    price: 38.00,
    image: '/products/rapsodija-okusa.jpeg',
    category: 'Poklon paketi',
    unit: 'kom',
  },
  {
    id: '20',
    name: 'Zagorski Mediteran',
    description: 'Elegantna poklon kutija koja spaja Zagorje i Mediteran: Višnjevac 0.2L, Liker od Zagorskih Maslina 0.5L i Haskap liker 0.2L — ukupno tri bočice u slamici s crvenom mašnom. Idealno za posebne darove.',
    price: 30.00,
    image: '/products/zagorski-mediteran.jpeg',
    category: 'Poklon paketi',
    unit: 'kom',
  },
];
